/**
 * @file board_config.h
 * @author Markus Blechschmidt (blechschmidt@simplexion.de)
 * @brief Autogenerated board configuration file
 * @version 0.1
 * @date 2023-04-06
 *
 * @copyright Copyright (c) 2023 Simplexion GmbH
 *
 */

#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_NAME ("RTL8762CKF-Dev-Board")
#define MCU_NAME ("RTL8762CKF")

#define BUTTON_PAD      (P1_7)
#define LED_PAD         (P4_3)
#define RX_PAD          (P3_1)
#define TX_PAD          (P3_0)

#endif // BOARD_CONFIG_H
